// Cryptocurrency icon mappings and helper functions

const ICON_MAPPINGS: Record<string, string> = {
  // Common symbol variations
  'BTC': 'btc',
  'ETH': 'eth',
  'BNB': 'bnb',
  'SOL': 'sol',
  'XRP': 'xrp',
  'USDC': 'usdc',
  'ADA': 'ada',
  'AVAX': 'avax',
  'DOGE': 'doge',
  'DOT': 'dot',
  'MATIC': 'matic',
  'SHIB': 'shib',
  'TRX': 'trx',
  'LINK': 'link',
  'UNI': 'uni',
  'LTC': 'ltc',
  'FTM': 'ftm',
  'NEAR': 'near',
  'ATOM': 'atom',
  'XLM': 'xlm',
  'BCH': 'bch',
  'ALGO': 'algo',
  'VET': 'vet',
  'MANA': 'mana',
  'SAND': 'sand',
  'AXS': 'axs',
  'FIL': 'fil',
  'THETA': 'theta',
  'EGLD': 'egld',
  'XMR': 'xmr',
  'AAVE': 'aave',
  'GRT': 'grt',
  'CRV': 'crv',
  'MKR': 'mkr',
  'SNX': 'snx',
  'COMP': 'comp',
  'YFI': 'yfi',
  'SUSHI': 'sushi',
  'ZEC': 'zec',
  'DASH': 'dash',
  'ENJ': 'enj',
  'BAT': 'bat',
  'CHZ': 'chz',
  'GALA': 'gala',
  'ONE': 'one',
  'KSM': 'ksm',
  'ZIL': 'zil',
  'IOTA': 'iota',
  'WAVES': 'waves',
  'QTUM': 'qtum',
  'OMG': 'omg',
  'ANKR': 'ankr',
  'CELO': 'celo',
  'AR': 'ar',
  'RUNE': 'rune',
  'KAVA': 'kava',
  'BAND': 'band',
  'SXP': 'sxp',
  'ALPHA': 'alpha',
  'LUNA': 'luna',
  'LUNC': 'lunc',
  'APE': 'ape',
  'GMT': 'gmt',
  'OP': 'op',
  'INJ': 'inj',
  'STX': 'stx',
  'ARB': 'arb',
  'SUI': 'sui',
  'SEI': 'sei',
  'PEPE': 'pepe',
  'FLOKI': 'floki',
  'WLD': 'wld',
  'TIA': 'tia',
  '1000SATS': 'sats',
  'ORDI': 'ordi',
  'JUP': 'jup',
  'BONK': 'bonk',
  'WIF': 'wif',
  'ONDO': 'ondo',
  'ENA': 'ena',
  'PENDLE': 'pendle',
  'STRK': 'strk',
  'PIXEL': 'pixel',
  'PORTAL': 'portal',
  'CYBER': 'cyber',
  'MEME': 'meme',
  'TWT': 'twt',
  'CFX': 'cfx',
  'GMX': 'gmx',
  'IMX': 'imx',
  'SSV': 'ssv',
  'BLUR': 'blur',
  'AGIX': 'agix',
  'FET': 'fet',
  'OCEAN': 'ocean',
  'RSR': 'rsr',
  'LDO': 'ldo',
  'BAL': 'bal',
  'STORJ': 'storj',
  'CTSI': 'ctsi',
  'ALICE': 'alice',
  'YGG': 'ygg',
  'ILV': 'ilv',
  'DYDX': 'dydx',
  'RDNT': 'rdnt',
  'MASK': 'mask',
  'GALXE': 'galxe',
  'GAL': 'gal',
  'HFT': 'hft',
  'PHB': 'phb',
  'HOOK': 'hook',
  'MAGIC': 'magic',
  'HBAR': 'hbar',
  'FLOW': 'flow',
  'RPL': 'rpl',
  'GNS': 'gns',
  'SYN': 'syn',
  'VIB': 'vib',
  'PERP': 'perp',
  'RNDR': 'rndr',
  'LQTY': 'lqty',
  'ID': 'id',
  'ARK': 'ark',
  'EDU': 'edu',
  'FDUSD': 'fdusd',
  'TUSD': 'tusd',
  'USDP': 'usdp',
  'TOMO': 'tomo',
  'CELR': 'celr',
  'HOT': 'hot',
  'RVN': 'rvn',
  'PEOPLE': 'people',
  'ENS': 'ens',
  'LPT': 'lpt',
  'ROSE': 'rose',
  'JASMY': 'jasmy',
  'DUSK': 'dusk',
  'TLM': 'tlm',
  'REEF': 'reef',
  'API3': 'api3',
  'SFP': 'sfp',
  'FXS': 'fxs',
  'BLZ': 'blz',
  'BADGER': 'badger',
  'UNFI': 'unfi',
  'RAD': 'rad',
  'IDEX': 'idex',
  'KNC': 'knc',
  'SLP': 'slp',
  'SPELL': 'spell',
  'JOE': 'joe',
  'ACH': 'ach',
  'BICO': 'bico',
  'DAR': 'dar',
  'REN': 'ren',
  'SKL': 'skl',
  'FLM': 'flm',
  'NKN': 'nkn',
  'BEL': 'bel',
  'C98': 'c98',
  'LEVER': 'lever',
  'KDA': 'kda',
  'AMB': 'amb',
  'COMBO': 'combo',
  'MDT': 'mdt',
  'XVS': 'xvs',
  'AGLD': 'agld',
  'USTC': 'ustc',
  'QNT': 'qnt',
  'LUNA2': 'luna2',
  'ACA': 'aca',
  'XVG': 'xvg',
  'BAKE': 'bake',
  'GLMR': 'glmr',
  'WOO': 'woo',
  'ALPACA': 'alpaca',
  'T': 't',
  'ASTR': 'astr',
  'NBT': 'nbt',
  'GMM': 'gmm',
  'QUICK': 'quick',
  'MOVR': 'movr',
  'EOS': 'eos',
  'ICP': 'icp',
  'ZRX': 'zrx',
  '1INCH': '1inch',
  'FTT': 'ftt',
  'CAKE': 'cake',
  'NEO': 'neo',
  'PAXG': 'paxg',
  'KAS': 'kas',
  'TON': 'ton',
  'PYTH': 'pyth',
  'NOT': 'not',
  'IO': 'io',
  'ZK': 'zk',
  'ZRO': 'zro',
  'TAO': 'tao',
  'LISTA': 'lista',
  'BANANA': 'banana',
  'RENDER': 'render',
  'DOGS': 'dogs',
  'EURI': 'euri',
  'TURBO': 'turbo',
  'CATI': 'cati'
};

export function getCryptoIconUrl(symbol: string, size: number = 32): string {
  // Remove USDT, BUSD, etc. suffixes
  const cleanSymbol = symbol.replace(/USDT|BUSD|BNB|ETH|BTC$/g, '').toUpperCase();
  
  // Check if we have a mapping for this symbol
  const mappedSymbol = ICON_MAPPINGS[cleanSymbol] || cleanSymbol.toLowerCase();
  
  // Try multiple CDN sources in order of reliability
  const iconSources = [
    `https://raw.githubusercontent.com/spothq/cryptocurrency-icons/master/${size}/color/${mappedSymbol}.png`,
    `https://cryptoicons.org/api/icon/${mappedSymbol}/${size}`,
    `https://coinicons-api.vercel.app/api/icon/${mappedSymbol}`,
    `https://assets.coingecko.com/coins/images/1/${mappedSymbol}/small`,
  ];
  
  return iconSources[0];
}

export function getFallbackIconUrl(symbol: string, size: number = 32): string {
  const cleanSymbol = symbol.replace(/USDT|BUSD|BNB|ETH|BTC$/g, '');
  // Use UI Avatars as fallback with a nice gradient
  const colors = ['7c3aed', '2563eb', '0891b2', '059669', '84cc16', 'eab308', 'f97316', 'ef4444', 'ec4899'];
  const color = colors[cleanSymbol.charCodeAt(0) % colors.length];
  return `https://ui-avatars.com/api/?name=${cleanSymbol}&size=${size}&background=${color}&color=fff&bold=true`;
}